<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>Oci.Athena.DataSource.Hexin.DataViewer</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net481</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>default</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Oci.Athena.DataSource.Hexin">
      <HintPath>..\..\..\..\..\..\..\Downloads\Hexin.DataViewer.1.0\Oci.Athena.DataSource.Hexin.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="Oci.Athena.DataSource.Hexin.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>